name: 🔄 Upstream Sync

on:
  schedule:
    - cron: "0 4 * * *" # Runs at 04:00 UTC
  workflow_dispatch:

jobs:
  sync:
    name: ${{ github.event_name == 'workflow_dispatch' && '👆 Manual' || '⏱️ Cron' }}
    uses: binlab/github-toolbox/.github/workflows/upstream-sync.yml@main
    with:
      upstream_repo: "carlpett/terraform-provider-sops"
      upstream_branch: "master"
      target_branch: "master"
    secrets: inherit
